- name: Deploy da aplicação todolist
  hosts: app
  become: true  # Necessário para executar comandos com privilégio de superusuário
  tasks:
    # Instalar dependências necessárias (Docker e Git)
    - name: Atualizar o cache de pacotes APT
      apt:
        update_cache: true

    - name: Iniciar o serviço Docker
      service:
        name: docker
        state: started
        enabled: true

    # Clonar o repositório
    - name: Clonar repositório do GitHub
      git:
        repo: 'https://github.com/Chiet4/todoList_Atividade_Final.git'
        dest: '/home/ubuntu/Atividade-final'

    - name: Construir imagem Docker
      community.docker.docker_image:
        name: todolist:latest
        build:
          path: /home/ubuntu/Atividade-final  # Caminho completo para o diretório com o Dockerfile
          dockerfile: Dockerfile

    
    # Executar o contêiner Docker
    - name: Rodar o contêiner Docker
      community.docker.docker_container:
        name: todolist
        image: todolist:latest
        ports:
          - "8080:80"
